import { useEffect, useState } from "react";
import { Input, Button, Spin, message } from "antd";
import {  useNavigate } from "react-router-dom";
import { enable2FA, verify2FA } from "../../../api/users";
import { useSelector, useDispatch } from "react-redux";
import { userActions } from "../../../redux/userSlice";

const TwoFactorSetup = () => {
  
  const [qrCodeUrl, setQrCodeUrl] = useState("");
  const [verificationCode, setVerificationCode] = useState("");
  const [loading, setLoading] = useState(true);
  const { user } = useSelector((state) => state.users);
  const navigate = useNavigate();
  const dispatch = useDispatch();

  // Fetch QR Code when the page loads
  useEffect(() => {
    async function fetchQRCode() {
      try {
        const response = await enable2FA({ email: user.email });
        setQrCodeUrl(response.data);
      } catch (error) {
        message.error("Failed to load QR code");
      } finally {
        setLoading(false);
      }
    }

    fetchQRCode();

    if(user.is2FAEnabled){
      navigate('/profile-settings')
    }
    
  }, []);

  // Handle 2FA verification
  const handleVerify2FA = async () => {
    try {
      const response = await verify2FA({
        email: user.email,
        otp: verificationCode,
      });
      if (response.success) {
        message.success("2FA enabled successfully!");
        dispatch(userActions.setCurrentUser(response.data))
        navigate("/profile-settings");
      } else {
        message.error("Invalid verification code. Try again.");
      }
    } catch (error) {
      message.error("Verification failed. Please try again.");
    }
  };

  return (
    <div>
      <h2>Setup Two-Factor Authentication</h2>

      {loading ? (
        <Spin size="large" />
      ) : (
        <>
          <p>
            Use an app such as{" "}
            <a target="_blank" href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2">
              Google Authenticator
            </a>, 
            <a target="_blank" href="https://www.microsoft.com/en-in/security/mobile-authenticator-app"> Microsoft Authenticator</a> to scan the QR code below.
          </p>
          <img src={qrCodeUrl} alt="QR Code" style={{ width: "200px" }} />

          <p>Enter the code generated by your authenticator app:</p>
          <Input
            placeholder="Enter 2FA Code"
            value={verificationCode}
            onChange={(e) => setVerificationCode(e.target.value)}
            style={{ width: "200px", marginBottom: "10px" }}
          />

          <br />
          <Button type="primary" onClick={handleVerify2FA}>
            Verify 2FA
          </Button>
        </>
      )}
    </div>
  );
};

export default TwoFactorSetup;
